### ISSUE TITLE
Why is bin/www throwing an error

### ISSUE THREAD

**Issue by manojk955** [sushantshekhar20/bot_api.ai#10]
running bin/www is throwing an error even though I followed the exact steps mentioned

C:\Users\........\bot-api.ai>node bin/www
module.js:549
    throw err;
    ^

Error: Cannot find module 'serve-favicon'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\......\bot-api.ai\app.js:3:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by sheksushant** [comment]
try running these commands : 

`$ npm i serve-favicon`
`$ npm i`
