### ISSUE TITLE
Cannot find module 'serve-favicon'

### ISSUE THREAD

**Issue by Primtek** [sushantshekhar20/bot_api.ai#13]
running on centOS 7

[root@ai bot-dialogflow-master]# node bin/www
module.js:549
    throw err;
    ^

Error: Cannot find module 'serve-favicon'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/primtek/bot-dialogflow-master/bot-dialogflow-master/app.js:3:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
[root@ai bot-dialogflow-master]#

**Comment by richardimms** [comment]
You have two choices, you can either use my fork where I have commented out the line that is causing this issue (line 3 of app.js) OR just uncomment line 19 of app.js and place your desired favicon under public with the name "favicon.ico".

**Comment by sheksushant** [comment]
FIxed #14 

Thanks @richardimms
